DATABASE_NAME = "db.json"
BOOKLIST_PATH = "booklist.txt"
BOOKLIST_JSON_PATH = "/home/starminalush/InMemoryDatabase/tests/utils/booklist_dict.json"
BOOKLIST_UPDATE_JSON_PATH = "/home/starminalush/InMemoryDatabase/tests/utils/booklist_update_dict.json"
URL = "http://127.0.0.1:5000"
DATABASE_DIRECTORY="data"